apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-mysql
  namespace: sqldb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: a2-mysqldb
        image: 867782315616.dkr.ecr.us-east-1.amazonaws.com/a2_mysql:v1.0
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
        - name: MYSQL_DATABASE
          value: employees
