apiVersion: v1
kind: Pod
metadata:
  name: a2-mysql
spec:
  containers:
  - name: a2-mysql-container
    image: 867782315616.dkr.ecr.us-east-1.amazonaws.com/a2_mysql:v1.0
    ports:
    - containerPort: 3306
      protocol: TCP
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: pw
    - name: MYSQL_DATABASE
      value: employees
  