apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: a2-myapp-replicas
  namespace: webapp
  labels:
      app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: employee-myapp
        image: 867782315616.dkr.ecr.us-east-1.amazonaws.com/a2-my-app:v1.0
        ports:
        - containerPort: 8080
        env: 
        - name: DBHOST
          value: "mysql-service.sqldb.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pw"
        - name: APP_COLOR
          value: "blue"  
        - name: DATABASE
          value: "employees"
          
